export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export type GET_DOCUMENTS = typeof GET_DOCUMENTS;

export const UPDATE_DOCUMENTS = 'UPDATE_DOCUMENTS';
export type UPDATE_DOCUMENTS = typeof UPDATE_DOCUMENTS;

export const CLEAR_STATE = 'CLEAR_STATE';
export type CLEAR_STATE = typeof CLEAR_STATE;
